### ISSUE TITLE
script issue 

### ISSUE THREAD

**Issue by Dhirendramohanjha** [prajjwal1/autonomous-object-detection#10]
In optimal_transport.ipynb i am not finding any detection script so, 
 from detection.unet import * & from detection import transform are call in this script. 
please share that script also.
please share ya upload in repo

**Comment by prajjwal1** [comment]
Users are not required to use `optimal_transport` notebook. It is there only for reference purpose. I created that for experimenting with OT algorithms. Ignore this notebook.

**Comment by Dhirendramohanjha** [comment]
> Users are not required to use `optimal_transport` notebook. It is there only for reference purpose. I created that for experimenting with OT algorithms. Ignore this notebook.

Thank you
