### ISSUE TITLE
Issue in evaluating model for BDD_100K

### ISSUE THREAD

**Issue by godatta** [prajjwal1/autonomous-object-detection#14]
Hi,

Thanks for uploading the code. I followed your instructions, and tried to evaluate your pretrained base model for BDD_100K, but got the following error from coco api. Can you please help me out?
<img width="1084" alt="Screen Shot 2021-04-12 at 1 05 05 AM" src="https://user-images.githubusercontent.com/46044371/114361582-20231080-9b2b-11eb-88d7-cae5fab40d68.png">

**Comment by akfmdl** [comment]
BDD100k folder structure is
`~/bdd100k/bdd100k_images_100k/images/100k`
not
`~/bdd100k/images/100k`
