### ISSUE TITLE
Is the pre-trained model provided for BDD100K trained using Resnet-50 model ?

### ISSUE THREAD

**Issue by AmanGoyal99** [prajjwal1/autonomous-object-detection#15]
Greetings,

Is the pre-trained model provided for BDD100K trained using Resnet-50 model ? 
If not, then can I train Resnet-50 model as a backbone on BDD100K using your code ?

Thanks

**Comment by prajjwal1** [comment]
BDD100K is primarily a an object detection dataset. So this repo provides support for using FasterRCNN which has  a ResNet50 backbone.

1. Yes. I've provided both fine-trained models for IDD and BDD100K.
2. By default, FasterRCNN in this repo uses ResNet50 as a backbone. Check out `train_baseline.py` along with setting data up information in README to train your model. You might have to change few things if you do not want to use FasterRCNN.

**Comment by AmanGoyal99** [comment]
> BDD100K is primarily a an object detection dataset. So this repo provides support for using FasterRCNN which has a ResNet50 backbone.
> 
> 1. Yes. I've provided both fine-trained models for IDD and BDD100K.
> 2. By default, FasterRCNN in this repo uses ResNet50 as a backbone. Check out `train_baseline.py` along with setting data up information in README to train your model. You might have to change few things if you do not want to use FasterRCNN.

Hey, thanks for responding. So I actually just want to train Resnet-50 on BDD100K detection dataset. I will use the trained weights for knowledge distillation then. So I just need to train it as a backbone actually. Kindly let me know if that is possible through your repo and if possible provide me any suggestions on achieving the same.

Thanks

**Comment by prajjwal1** [comment]
This object is primarily meant for object detection. If you want to train `resnet50`, you can straightaway use `torchvision`. Closing it because it is not related to the codebase.
