### ISSUE TITLE
Make pretrained models available?

### ISSUE THREAD

**Issue by tloki** [prajjwal1/autonomous-object-detection#2]
Do you plan on releasing weights of your state-of-the-art trined model?

**Comment by prajjwal1** [comment]
I can release the pre-trained models but I don't have spare cloud storage available.

**Comment by tloki** [comment]
How big are pre-trained models? Is maybe a github LFS suitable solution? Also I see many people using gdrive/mega for public sharing of weights...

**Comment by prajjwal1** [comment]
Well the model is not that big (330 MB). I don't have any free Gdrive space available. If there's a way I can share it with you, happy to upload it there.

**Comment by tloki** [comment]
since I have no idea of other way to put weights, here is a public link to my Google Drive (with upload permission) with 10+ GB of free space:

https://drive.google.com/drive/folders/19UzhsQkPdD7c7FMSwao5XwdIwS0JV-1R?usp=sharing

**Comment by prajjwal1** [comment]
I've uploaded the baseline model trained on BDD-100k. Feel free to use it for academic research purposes. I'm closing this issue for now.

**Comment by prajjwal1** [comment]
> since I have no idea of other way to put weights, here is a public link to my Google Drive (with upload permission) with 10+ GB of free space:
> 
> https://drive.google.com/drive/folders/19UzhsQkPdD7c7FMSwao5XwdIwS0JV-1R?usp=sharing

Do you plan on keeping the link public ?

**Comment by saadhana** [comment]
Are the model files now public? 
Could you also share the pre-trained weights for the India Driving Dataset please?

**Comment by prajjwal1** [comment]
Please check the README again, I've added the link for pretrained models

**Comment by saadhana** [comment]
Thanks a lot for uploading the model, Prajjwal!
