### ISSUE TITLE
Did you use val_annotation of target domain for training

### ISSUE THREAD

**Issue by XuShoweR** [prajjwal1/autonomous-object-detection#3]
Did you use val_annotation of target domain for training, if not how the new Domain T head  works?

`model.roi_heads.box_predictor = torchvision.models.detection.faster_rcnn.FastRCNNPredictor(in_features, num_classes) # replace the pre-trained head with a new one`

I found this line in your code, but I don't know how to use it without training

**Comment by prajjwal1** [comment]
Yes, I used it. You basically have to replace this linear layer as per your requirements from Domain T.
