### ISSUE TITLE
flow of your model?

### ISSUE THREAD

**Issue by Dhirendramohanjha** [prajjwal1/autonomous-object-detection#4]
@Hi,

I have invoice data 100 different company and their templates are different from every company, in every week I found new 5 company invoice data with different kinds of templates, so we do not train again and again with whole data because of its takes lots of time and after some months we can't train with the whole bunch of data.
So please can I used your model, and please how I start with your model
I found some difficulties in the train with our custom data instead of your data and please share the baseline model trained on BDD-100k.
Can I use these techniques for yolo model also.
 thank you

**Comment by Dhirendramohanjha** [comment]
> @hi,
> 
> I have invoice data 100 different company and their templates are different from every company, in every week I found new 5 company invoice data with different kinds of templates, so we do not train again and again with whole data because of its takes lots of time and after some months we can't train with the whole bunch of data.
> So please can I used your model, and please how I start with your model
> I found some difficulties in the train with our custom data instead of your data and please share the baseline model trained on BDD-100k.
> Can I use these techniques for yolo model also.
> thank you

**Comment by prajjwal1** [comment]
Please find the instructions in README. I have also made the pretrained models available. Closing this as this issue is not related to any bug/ relevant problem.
