### ISSUE TITLE
something is wrong with bdd100k json format

### ISSUE THREAD

**Issue by kaishijeng** [prajjwal1/autonomous-object-detection#8]
When I run evelaution_baseline.py, I got an error in bdd.py below. It is related to parse json file.
anno_data in line 79 of bdd.py is not a list. It is a dict which has 4 keys:
categories
images
annotations
type
But in your code, you use it as list and is not able to anno_data[i]['label]
Do you know why my json is different from your code?
Error:
>>
Loading files
Evaluation on Berkeley Deep Drive
categories
images
annotations
type
  0%|                                                                                            | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./evaluation_baseline.py", line 61, in <module>
    val_dataset = BDD(bdd_img_path_list, val_anno_json_path)
  File "/home/henry.jeng/ML/autonomous-object-detection/datasets/bdd.py", line 82, in __init__
    self.total_bboxes_list, self.total_labels_list = get_ground_truths(
  File "/home/henry.jeng/ML/autonomous-object-detection/datasets/bdd.py", line 38, in get_ground_truths
    for j in range(len(anno_data[i]["labels"])):
KeyError: 0

**Comment by prajjwal1** [comment]
If I remember correctly, it was a list of dictionary.

**Comment by kaishijeng** [comment]
Ignore this because I use a json which has been converted to coco style.
