### ISSUE TITLE
map=0 for bdd100k evaluation

### ISSUE THREAD

**Issue by kaishijeng** [prajjwal1/autonomous-object-detection#9]
I ran evaluation using your pretrained model on bdd100k dataset and got map=0.
Inference on single image looks OK. Any idea why this happens?

Thanks,

**Comment by prajjwal1** [comment]
Is the model in eval mode ? Also please check the inputs once. I used Torchvision 0.4 for this.

**Comment by prajjwal1** [comment]
Closing it, since no response received.

**Comment by godatta** [comment]
Hi,

I also ran into the same problem. Got AP=0. How can I make sure the model is in eval mode?
